### ISSUE TITLE
Bloons tower defense 6 siphon boss concept request

### ISSUE THREAD

**Issue by Airuniform** [WarperSan/BTD6-Mods#1]
Hi WarperSan, I have been trying to get people to know about a concept boss I made for many months now, it was generally a pain to deal with, but I was recently brought to you, the creator of the 5 custom boss mod. You are probably perfect for this as you've done requests before. Can you make a mod of siphon so people actually can interact with it? As for the design, I just copied and pasted it from a word document I typed up.

Bloons tower defense 6 boss concept

Name: Siphon the eternal

Ability: upon reaching a skull of health, Siphon will take a buff from a tower 
( the tower will not be deleted, but also can't be sold during this process), absorbs it within itself, clones the last round, and gives the buff to the round at which the buff originated. Some towers give buffs no other towers give( unique buffs), others give buffs that many others also give( general buffs), and some don't give any buffs at all.

Some towers in this list don't have buffs because I can't come up with any. If you have ideas, comment below.

Some of the general buffs overlap. I won't type that out because this document is already long enough as is and there will be an entire section after this list of buffs about the bosses lore if they actually existed in game.

List of buffs
Paragons: the shield: spawns a shield around siphon that normal projectiles, like the navarch's cannons and the Apex plasma master juggernaut need to break down to deal damage to the boss. Hitscan or aoe attacks, like the orbiting glaives of the Glaive dominus or the sticky bomb of the Ascended shadow can damage the boss in this state.( general/ exclusive)
Ultra juggernaut: 2x bloon spawns upon death( unique)
Plasma monkey fan club: none
Crossbow master: bloons move much faster, speed buff( general)
Glaive lord: none
Perma charge: speed buff( general)
Moab domination: BAD effect: gives every bloon summoned immunity to slows, one shots, stuns and stalls.( general)
Bloon crush: BAD effect( general)
Moab eliminator: Increases Moab health. Strength buff.( general)
Bomb blitz: none
Inferno ring: can't decide( I have ideas but can't pick between them.)
Super maelstrom: none
Tack zone: speed buff( general)
Ice monkey 5th tiers: BAD effect( general)
Bloon solver: none
Glue storm: none
Super glue: BAD effect( general)
Cripple moab: BAD effect( general)
Elite Sniper: speed buff( general)
Elite defender: speed buff( general)
Energizer: bloons resistant to abilities( exclusive)
Preemptive strike: strength buff( general)
Sub commander: can't decide
Carrier flagship: strength buff ( general)
Pirate lord: BAD effect( general)
Trade empire: none
Sky shredder: speed buff( general)
Tsar bomba: none
Flying fortress: speed buff( general)
Apache prime: strength buff( general)
Special poperations: none
Comanche commander: BAD effect( general)
The biggest one: bloons have a stunning explosion that scales with their size( exclusive)
Pop and awe: BAD effect( general)
Blooncineration: none
Ray of doom: none
Mad: strength buff( general)
Bloon exclusion zone: speed buff( general)
Archmage: speed buff( general)
Wizard lord Phoenix: none
Prince of darkness: none
Super monkey 5th tiers: speed buff minus bottom path. Bottom Path gives strength buff.
Grandmaster ninja: speed buff( general)
Grand saboteur: BAD effect( general)
Master bomber: strength buff( general)
Permanent brew: strength buff( general)
Total transformation: none
Bloon master alchemist: BAD effect( general)
Superstorm: BAD effect( general)
Spirit of the forest: none
Avatar of wrath: speed buff( general)
Banana farm 5th tiers: none
Spike factory 5th tiers: strength buffs( general)
Village 5th tiers: none from top or bottom, but middle gives speed buff.
Sentry champion: speed buff( general)
Ultra boost: speed buff( general)
XXXL trap: BAD effect( general)

**Comment by Airuniform** [comment]
the boss isn't immune to damage during the absorption period, but the animation and effect will finish

**Comment by Airuniform** [comment]
Rounds overlap on top of each other instead of overriding the last one sent.

**Comment by WarperSan** [comment]
Thanks for the idea !

I would prefer if you post this boss idea in the Suggestions channel on the Discord Server "1330 Studios" so that me or another modder can bring that idea into the game.
